language: cpp
script:
- cmake -H. -B_build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Coverage -DBUILD_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=_install -DCPACK_GENERATOR="TGZ"
- cmake --build _build
- cmake --build _build --target install
- cmake --build _build --target test -- ARGS=--verbose
- cmake --build _build --target unit_tests_coverage 
- cmake --build _build --target package
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - lcov
