version: 1.0.{build}

image: 
  - Ubuntu
  
before_build:
  - cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DCPACK_GENERATOR="TGZ" 
  
build_script:
  - cmake --build _build
  - cmake --build _build --target install
  # - cmake --build _build --target test
  
after_build:
  - cd _build 
  - cpack -G "TGZ" 
  - cd ..
  - cmake --build _build --target package 

# test_script:
  # - cd _build
  # - ./check -s -r compact
